# Generated by Django 2.2.4 on 2019-10-21 20:10

from django.db import migrations, models
import django.db.models.deletion
from  django.apps import apps
def valores_iniciales(apps, schema_editor):
    ''' Cargamos los valores iniciales que necesitamos para poder trabajar '''
    
    #Cargamos los valores de empresa por Default.
    Empresa = apps.get_model('configuraciones', 'empresa')
    empresa = Empresa( razon_social = 'Default',
                       cuit = '30-00000000-0',
                       direccion_fiscal = 'Av. Siempreviva 742',
                       direccion_deposito = 'Av. Siempreviva 730, (Flnds)',
                       ingresos_brutos = '303030'
                        )
    empresa.save()
    print('\n[+] Se ha creado la empresa Default...')

    # cargamos las fuentes.
    Fuentes = apps.get_model('configuraciones', 'Fuentes')
    listFonts = ['Helvetica', 'Arial' ,'sans-serif']
    for fonts in listFonts:
        objFont = Fuentes(nombre = fonts)
        objFont.save()
    print('[+] Se han cargado una serie estandar de fuentes...')
    # Ahora vamos a cargar las configuraciones de impresion remito.
    ConfigImpresion = apps.get_model('configuraciones', 'ConfigImpresionRemito')
    if len(ConfigImpresion.objects.all()) == 0:
        obj = ConfigImpresion(nombre = 'Impresora Default', 
                                size_font_cabecera = 11, 
                                type_font_cabecera_id = 1, 
                                size_font_cuerpo = 10, 
                                type_font_cuerpo_id = 1, 
                                size_font_pie = 9, 
                                type_font_pie_id = 1, 
                                pos_x_fecha = 385, 
                                pos_y_fecha = 735, 
                                pos_x_razon_social = 100, 
                                pos_y_razon_social = 655, 
                                pos_x_condicion = 100, 
                                pos_y_condicion = 635, 
                                pos_x_direccion_f = 390, 
                                pos_y_direccion_f = 655, 
                                pos_x_cuit = 390, 
                                pos_y_cuit = 635, 
                                pos_y_comienzo_cuerpo = 560, 
                                pos_x_comienzo_cuerpo = 45, 
                                pos_y_bultos = 180, 
                                pos_x_bultos = 315, 
                                pos_y_direccion_entrega = 168, 
                                pos_x_direccion_entrega = 315, 
                                pos_y_ordencompra = 152, 
                                pos_x_ordencompra= 315
                                )
        obj.save()
        print('[+] Se ha creado una plantilla de impresión por defecto...')

        
class Migration(migrations.Migration):

   

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, unique=True)),
                ('cuit', models.CharField(max_length=50, unique=True)),
                ('direccion_fiscal', models.CharField(max_length=255)),
                ('direccion_deposito', models.CharField(max_length=255)),
                ('ingresos_brutos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigImpresionRemito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('size_font_cabecera', models.IntegerField()),
                ('size_font_cuerpo', models.IntegerField()),
                ('size_font_pie', models.IntegerField()),
                ('pos_x_fecha', models.IntegerField()),
                ('pos_y_fecha', models.IntegerField()),
                ('pos_x_razon_social', models.IntegerField()),
                ('pos_y_razon_social', models.IntegerField()),
                ('pos_x_condicion', models.IntegerField()),
                ('pos_y_condicion', models.IntegerField()),
                ('pos_x_direccion_f', models.IntegerField()),
                ('pos_y_direccion_f', models.IntegerField()),
                ('pos_x_cuit', models.IntegerField()),
                ('pos_y_cuit', models.IntegerField()),
                ('pos_y_comienzo_cuerpo', models.IntegerField()),
                ('pos_x_comienzo_cuerpo', models.IntegerField()),
                ('pos_y_bultos', models.IntegerField()),
                ('pos_x_bultos', models.IntegerField()),
                ('pos_y_direccion_entrega', models.IntegerField()),
                ('pos_x_direccion_entrega', models.IntegerField()),
                ('pos_y_ordencompra', models.IntegerField()),
                ('pos_x_ordencompra', models.IntegerField()),
                ('type_font_cabecera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCabecera_remito', to='configuraciones.Fuentes')),
                ('type_font_cuerpo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCuerpo_remito', to='configuraciones.Fuentes')),
                ('type_font_pie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentePie_remito', to='configuraciones.Fuentes')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigImpresionOrdenTraslado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('size_font_cabecera', models.IntegerField()),
                ('size_font_cuerpo', models.IntegerField()),
                ('size_font_pie', models.IntegerField()),
                ('pos_x_fecha', models.IntegerField()),
                ('pos_y_fecha', models.IntegerField()),
                ('pos_x_razon_social', models.IntegerField()),
                ('pos_y_razon_social', models.IntegerField()),
                ('pos_x_condicion', models.IntegerField()),
                ('pos_y_condicion', models.IntegerField()),
                ('pos_x_direccion_f', models.IntegerField()),
                ('pos_y_direccion_f', models.IntegerField()),
                ('pos_x_cuit', models.IntegerField()),
                ('pos_y_cuit', models.IntegerField()),
                ('pos_y_comienzo_cuerpo', models.IntegerField()),
                ('pos_x_comienzo_cuerpo', models.IntegerField()),
                ('pos_y_bultos', models.IntegerField()),
                ('pos_x_bultos', models.IntegerField()),
                ('pos_y_direccion_entrega', models.IntegerField()),
                ('pos_x_direccion_entrega', models.IntegerField()),
                ('pos_y_ordencompra', models.IntegerField()),
                ('pos_x_ordencompra', models.IntegerField()),
                ('type_font_cabecera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCabecera_ordentraslado', to='configuraciones.Fuentes')),
                ('type_font_cuerpo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCuerpo_ordentraslado', to='configuraciones.Fuentes')),
                ('type_font_pie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentePie_ordentraslado', to='configuraciones.Fuentes')),
            ],
        ),
                
                
                migrations.RunPython(valores_iniciales),

    ]
