# Generated by Django 2.2.4 on 2019-10-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, unique=True)),
                ('cuit', models.CharField(max_length=50, unique=True)),
                ('direccion_fiscal', models.CharField(max_length=255)),
                ('direccion_deposito', models.CharField(max_length=255)),
                ('ingresos_brutos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigImpresionRemito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('size_font_cabecera', models.IntegerField()),
                ('size_font_cuerpo', models.IntegerField()),
                ('size_font_pie', models.IntegerField()),
                ('pos_x_fecha', models.IntegerField()),
                ('pos_y_fecha', models.IntegerField()),
                ('pos_x_razon_social', models.IntegerField()),
                ('pos_y_razon_social', models.IntegerField()),
                ('pos_x_condicion', models.IntegerField()),
                ('pos_y_condicion', models.IntegerField()),
                ('pos_x_direccion_f', models.IntegerField()),
                ('pos_y_direccion_f', models.IntegerField()),
                ('pos_x_cuit', models.IntegerField()),
                ('pos_y_cuit', models.IntegerField()),
                ('pos_y_comienzo_cuerpo', models.IntegerField()),
                ('pos_x_comienzo_cuerpo', models.IntegerField()),
                ('pos_y_bultos', models.IntegerField()),
                ('pos_x_bultos', models.IntegerField()),
                ('pos_y_direccion_entrega', models.IntegerField()),
                ('pos_x_direccion_entrega', models.IntegerField()),
                ('pos_y_ordencompra', models.IntegerField()),
                ('pos_x_ordencompra', models.IntegerField()),
                ('type_font_cabecera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCabecera_remito', to='configuraciones.Fuentes')),
                ('type_font_cuerpo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCuerpo_remito', to='configuraciones.Fuentes')),
                ('type_font_pie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentePie_remito', to='configuraciones.Fuentes')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigImpresionOrdenTraslado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('size_font_cabecera', models.IntegerField()),
                ('size_font_cuerpo', models.IntegerField()),
                ('size_font_pie', models.IntegerField()),
                ('pos_x_fecha', models.IntegerField()),
                ('pos_y_fecha', models.IntegerField()),
                ('pos_x_razon_social', models.IntegerField()),
                ('pos_y_razon_social', models.IntegerField()),
                ('pos_x_condicion', models.IntegerField()),
                ('pos_y_condicion', models.IntegerField()),
                ('pos_x_direccion_f', models.IntegerField()),
                ('pos_y_direccion_f', models.IntegerField()),
                ('pos_x_cuit', models.IntegerField()),
                ('pos_y_cuit', models.IntegerField()),
                ('pos_y_comienzo_cuerpo', models.IntegerField()),
                ('pos_x_comienzo_cuerpo', models.IntegerField()),
                ('pos_y_bultos', models.IntegerField()),
                ('pos_x_bultos', models.IntegerField()),
                ('pos_y_direccion_entrega', models.IntegerField()),
                ('pos_x_direccion_entrega', models.IntegerField()),
                ('pos_y_ordencompra', models.IntegerField()),
                ('pos_x_ordencompra', models.IntegerField()),
                ('type_font_cabecera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCabecera_ordentraslado', to='configuraciones.Fuentes')),
                ('type_font_cuerpo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCuerpo_ordentraslado', to='configuraciones.Fuentes')),
                ('type_font_pie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentePie_ordentraslado', to='configuraciones.Fuentes')),
            ],
        ),
    ]
