# Generated by Django 2.2.4 on 2019-09-16 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_auto_20190909_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configimpresionremito',
            old_name='pos_y_comiezo_cuerpo',
            new_name='pos_y_comienzo_cuerpo',
        ),
        migrations.AlterField(
            model_name='configimpresionremito',
            name='type_font_cabecera',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCabecera', to='configuraciones.Fuentes'),
        ),
        migrations.AlterField(
            model_name='configimpresionremito',
            name='type_font_cuerpo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuenteCuerpo', to='configuraciones.Fuentes'),
        ),
        migrations.AlterField(
            model_name='configimpresionremito',
            name='type_font_pie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentePie', to='configuraciones.Fuentes'),
        ),
    ]
