# Generated by Django 2.2.4 on 2020-08-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200812_0205'),
        ('venta', '0007_auto_20191210_0913'),
    ]

    operations = [
    ]
