# Generated by Django 2.2.4 on 2020-08-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0001_initial'),
        ('venta', '0008_merge_20200812_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productolineasrm',
            name='cantidad_confirmada',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(max_length=50, unique=True)),
                ('tipo_documento', models.CharField(choices=[('Remito', 'Remito'), ('OrdenTraslado', 'Orden de Traslado')], default='AVION', max_length=50)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('conformado', models.BooleanField(default=False)),
                ('anulado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Cliente')),
                ('formato_de_impresion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.FormatodeImpresion')),
            ],
        ),
    ]
