# Generated by Django 2.2.4 on 2019-08-25 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Cliente')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Cronograma')),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(max_length=50, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Cliente')),
                ('ordencompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.OrdenCompra')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLineasRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas', models.IntegerField(default=1)),
                ('cantidad', models.IntegerField()),
                ('total_unidades', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Producto')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Remito')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLineasOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('OrdenCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.OrdenCompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Producto')),
            ],
        ),
    ]
