# Generated by Django 2.2.4 on 2020-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='id_registro',
            field=models.IntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
    ]
