# Generated by Django 2.2.4 on 2019-11-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadorRemito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_aceptada', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Producto')),
                ('remito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Remito')),
            ],
        ),
    ]
