# Generated by Django 2.2.4 on 2020-08-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productolineasrm',
            name='cantidad_confirmada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
