# Generated by Django 2.2.4 on 2019-08-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productolineasrm',
            name='cajas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productolineasrm',
            name='total_unidades',
            field=models.IntegerField(),
        ),
    ]
