# Generated by Django 2.2.4 on 2020-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_movimientos_id_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='productolineasrm',
            name='pendientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='id_registro',
            field=models.IntegerField(default=0),
        ),
    ]
