# Generated by Django 2.2.4 on 2019-12-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0001_initial'),
        ('venta', '0002_consolidadorremito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsolidadorRemito',
            new_name='ConformadorRemito',
        ),
    ]
