# Generated by Django 2.2.4 on 2019-09-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20190825_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatodeImpresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
