# Generated by Django 2.2.4 on 2019-12-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20191202_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConformadorRemito',
        ),
    ]
