# Generated by Django 2.2.4 on 2019-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_delete_conformadorremito'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='cantidad_confirmada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
