# Generated by Django 2.2.4 on 2019-09-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_remito_formato_de_impresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='conformado',
            field=models.BooleanField(default=False),
        ),
    ]
