# Generated by Django 2.2.4 on 2019-09-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_remito_conformado'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
