# Generated by Django 2.2.4 on 2019-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_remito_cantidad_confirmada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='cantidad_confirmada',
            field=models.IntegerField(default=0),
        ),
    ]
