# Generated by Django 2.2.4 on 2019-12-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20191202_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remito',
            name='cantidad_confirmada',
        ),
        migrations.AddField(
            model_name='productolineasrm',
            name='cantidad_confirmada',
            field=models.IntegerField(default=0),
        ),
    ]
