# Generated by Django 2.2.4 on 2019-09-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0007_auto_20190908_2025'),
        ('venta', '0006_remito_anulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTraslado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('conformado', models.BooleanField(default=False)),
                ('anulado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Cliente')),
                ('formato_de_impresion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.FormatodeImpresion')),
                ('ordencompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.OrdenCompra')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLineasOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total_unidades', models.IntegerField()),
                ('ordentraslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.OrdenTraslado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Producto')),
            ],
        ),
    ]
