# Generated by Django 2.2.4 on 2019-10-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_ordentraslado_productolineasot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentraslado',
            name='formato_de_impresion',
        ),
        migrations.RemoveField(
            model_name='remito',
            name='formato_de_impresion',
        ),
    ]
