# Generated by Django 2.2.4 on 2019-10-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20191012_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
