# Generated by Django 2.2.4 on 2020-08-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_auto_20200812_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productolineasoc',
            name='fecha_entrega',
            field=models.DateField(default='1983-01-17'),
        ),
    ]
