# Generated by Django 2.2.4 on 2020-08-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='orden_de_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.OrdenCompra'),
        ),
    ]
