# Generated by Django 2.2.4 on 2019-10-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_ordencompra_circuito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productolineasot',
            name='ordentraslado',
        ),
        migrations.RemoveField(
            model_name='productolineasot',
            name='producto',
        ),
        migrations.DeleteModel(
            name='OrdenTraslado',
        ),
        migrations.DeleteModel(
            name='ProductoLineasOT',
        ),
    ]
