# Generated by Django 2.2.4 on 2019-10-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_auto_20191015_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='tipo_documento',
            field=models.CharField(choices=[('Remito', 'Remito'), ('OrdenTraslado', 'Orden de Traslado')], default='', max_length=50),
        ),
    ]
