# Generated by Django 2.2.4 on 2019-10-16 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_remito_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
