# Generated by Django 2.2.4 on 2019-10-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_auto_20191016_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='tipo_documento',
            field=models.CharField(choices=[('Remito', 'Remito'), ('OrdenTraslado', 'Orden de Traslado')], default='Remito', max_length=50),
        ),
    ]
