# Generated by Django 2.2.4 on 2019-10-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_auto_20191017_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
