# Generated by Django 2.2.4 on 2019-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_cronograma_fecha_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='fecha_finalizacion',
            field=models.DateField(default='1983-01-17'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='fecha_inicio',
            field=models.DateField(default='1983-01-17'),
        ),
    ]
