# Generated by Django 2.2.4 on 2019-08-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
