# Generated by Django 2.2.4 on 2019-09-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0004_auto_20190905_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(default='Responsable Inscripto', max_length=100),
        ),
    ]
