# Generated by Django 2.2.4 on 2019-09-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0005_cliente_condicion_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=5, unique=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('relacion_de_medida', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineaInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medida1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medida2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medida3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('familiainsumos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.FamiliaInsumos')),
                ('peso_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gral.Peso')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
                ('lineainsumos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.LineaInsumos')),
            ],
        ),
        migrations.CreateModel(
            name='Cuerpos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=5, unique=True)),
                ('cantidad_medidas', models.IntegerField()),
                ('medicion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Medicion')),
            ],
        ),
    ]
