# Generated by Django 2.2.4 on 2019-09-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0006_cuerpos_familiainsumos_insumo_lineainsumos_medicion_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaPeso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medida1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medida2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medida3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='lineaproducto',
            old_name='FamiliaProducto_id',
            new_name='familiaproducto_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Etiqueta_id',
            new_name='etiqueta_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='LineaProducto_Id',
            new_name='lineaproducto_Id',
        ),
        migrations.RemoveField(
            model_name='lineainsumos',
            name='medida1',
        ),
        migrations.RemoveField(
            model_name='lineainsumos',
            name='medida2',
        ),
        migrations.RemoveField(
            model_name='lineainsumos',
            name='medida3',
        ),
        migrations.RemoveField(
            model_name='lineainsumos',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='lineainsumos',
            name='peso_id',
        ),
        migrations.AddField(
            model_name='lineaproducto',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.AddField(
            model_name='insumos',
            name='lineainsumos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.LineaInsumos'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='medida_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gral.Medicion'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='peso_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gral.Peso'),
        ),
        migrations.AddField(
            model_name='peso',
            name='familiapeso_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gral.FamiliaPeso'),
            preserve_default=False,
        ),
    ]
