# Generated by Django 2.2.4 on 2019-10-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gral', '0007_auto_20190908_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresEconomicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('observacioens', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CondicionDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('valor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ValoresEconomicos_CondicionPago', to='gral.ValoresEconomicos')),
            ],
        ),
    ]
